<a href="https://colab.research.google.com/github/tikutaku69/colab_tamesi/blob/main/3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

リスト3.1

In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.32.1
aiohappyeyeballs                 2.3.5
aiohttp                          3.10.3
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.13
albumentations                   1.4.13
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.18.0
asn1crypto                       1.5.1
astropy                          6.1.2
astropy-iers-data                0.2024.8.12.0.32.58
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread              

リスト3.2

In [2]:
import torch

a = torch.tensor([1,2,3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


リスト3.3

In [ ]:
print("--- 2次元のリストから生成 ---")
b = torch.tensor([[1, 2],
                  [3, 4]])
print(b)

print("--- dtypeを指定し、倍精度のTensorにする ---")
c = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float64)
print(c)

print("--- 0から9までの数値で初期化 ---")
d = torch.arange(0, 10)
print(d)

print("--- すべての値が0の、2×3のTensor ---")
e = torch.zeros(2, 3)
print(e)

print("--- すべての値が乱数の、2×3のTensor ---")
f = torch.rand(2, 3)
print(f)

print("--- Tensorの形状はsizeメソッドで取得 ---")
print(f.size())

リスト3.4

In [3]:
print("--- -5から5までの連続値を10生成 ---")
g = torch.linspace(-5, 5, 10)
print(g)

--- -5から5までの連続値を10生成 ---
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


リスト3.5

In [4]:
print("--- Tensor → NumPy ---")
a = torch.tensor([[1, 2],
                  [3, 4.]])
b = a.numpy()
print(b)

print("--- NumPy → Tensor ---")
c = torch.from_numpy(b)
print(c)

--- Tensor → NumPy ---
[[1. 2.]
 [3. 4.]]
--- NumPy → Tensor ---
tensor([[1., 2.],
        [3., 4.]])


リスト3.6

In [ ]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("--- 2つのインデックスを指定 ---")
print(a[0, 1])

print("--- 範囲を指定 ---")
print(a[1:2, :2])

print("--- リストで複数のインデックスを指定 ---")
print(a[:, [0, 2]])

print("--- 3より大きい要素のみを指定 ---")
print(a[a>3])

print("--- 要素の変更 ---")
a[0, 2] = 11
print(a)

print("--- 要素の一括変更 ---")
a[:, 1] = 22
print(a)

print("--- 10より大きい要素のみ変更 ---")
a[a>10] = 33
print(a)

リスト3.7


In [ ]:
# ベクトル
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 行列
c = torch.tensor([[6, 5, 4],
                  [3, 2, 1]])

print("--- ベクトルとスカラーの演算 ---")
print(a + 3)

print("--- ベクトル同士の演算 ---")
print(a + b)

print("--- 行列とスカラーの演算 ---")
print(c + 2)

print("--- 行列とベクトルの演算（ブロードキャスト） ---")
print(c + a)

print("--- 行列同士の演算 ---")
print(c + c)

リスト3.8

In [ ]:
a = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])  # 1次元のTensor
b = a.view(2, 4)  # (2, 4)の2次元のTensorに変換
print(b)

リスト3.9

In [ ]:
c = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])  # 1次元のTensor
d = c.view(2, -1)  # (2, 4)の2次元のTensorに変換
print(d)

リスト3.10

In [ ]:
e = torch.tensor([[[0, 1],
                   [2, 3]],
                  [[4, 5],
                   [6, 7]]])  # 3次元のTensor
f = c.view(-1)  # 1次元のTensorに変換
print(f)

リスト3.11

In [ ]:
print("--- 要素数が1の次元が含まれる4次元のTensor ---")
g = torch.arange(0, 8).view(1, 2, 1, 4)
print(g)

print("--- 要素数が1の次元を削除 ---")
h = g.squeeze()
print(h)

リスト3.12

In [ ]:
print("--- 2次元のTensor ---")
i = torch.arange(0, 8).view(2, -1)
print(i)

print("--- 要素数が1の次元を、一番内側（2）に追加 ---")
j = i.unsqueeze(2)
print(j)

リスト3.13

In [ ]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])

print("--- 平均値を求める関数 ---")
m = torch.mean(a)
print(m.item())  # item()で値を取り出す

print("--- 平均値を求めるメソッド ---")
m = a.mean()
print(m.item())

print("--- 列ごとの平均値 ---")
print(a.mean(0))

print("--- 合計値 ---")
print(torch.sum(a).item())

print("--- 最大値 ---")
print(torch.max(a).item())

print("--- 最小値 ---")
print(torch.min(a).item())

リスト3.14

In [ ]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([1, 2, 3])

print("--- 和 ---")


print("--- 差 ---")


print("--- 積 ---")


print("--- 商（小数） ---")


print("--- 商（整数） ---")


print("--- 余り ---")

リスト3.15

In [ ]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([1, 2, 3])

print("--- 和 ---")
print(a + b)

print("--- 差 ---")
print(a - b)

print("--- 積 ---")
print(a * b)

print("--- 商（小数） ---")
print(a / b)

print("--- 商（整数） ---")
print(a // b)

print("--- 余り ---")
print(a % b)